-- Add real Teddy Kids staff from CSV data
-- Excluding salary information, using €1333.33 placeholder
-- Setting everyone under "Artem" initially

INSERT INTO public.staff (full_name, email, role, status, location) VALUES
('Adéla Jarošová', 'adelkajarosova@seznam.cz', 'Pedagogisch medewerker', 'active', 'Delft'),
('Alena Masselink', 'alena.masselink@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiderdorp'),
('Anastasia Christofori', 'anastasiachristofori@gmail.com', 'Pedagogisch medewerker', 'active', 'Delft'),
('Anna ten Dolle', 'annatendolle@hotmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Anna Cumbo', 'anna.cumbo98@gmail.com', 'Pedagogisch medewerker', 'active', '''s-Gravenhage'),
('Anna ti Dota', 'annaditota1997@gmail.com', 'Pedagogisch medewerker in ontwikkeling', 'active', 'Leiden'),
('Antonella Falcone', 'antonella_falcone_679@hotmail.com', 'Vestegingsmanager', 'active', '''s-Gravenhage'),
('Arianne van Beelen', 'ariannevanbeelen@live.nl', 'Pedagogisch medewerker', 'active', 'Katwijk'),
('Autumn Luijk', 'autumnluijk@outlook.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Bianca Martins Lopes', 'bianca.martins.lopes1@gmail.com', 'Pedagogisch medewerker', 'active', 'Haarlem'),
('Blanca Rocha Surribas', 'brochasurribas@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Celine Cornet', 'hoi.ikbenceline@gmail.com', 'Pedagogisch medewerker', 'active', 'Voorschoten'),
('Charessa Mae Magbanua', 'charessa_ar@icloud.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Charlene Daal', 'charlene19eli@hotmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Christian Antonio Ricco', 'christian.ricco93@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Christina Mouska', 'mouskaxristina@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Chrysovalantou Konstantia Tsigara', 'tsigarakonstantia@gmail.com', 'Pedagogisch medewerker', 'active', 'Haarlem'),
('Danique Hanzon', 'd.hanzon@icloud.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Denise Baak', 'denise_baak@live.nl', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Diana Dzhurova', 'dianayangel@abv.bg', 'Pedagogisch medewerker', 'active', '''s-Gravenhage'),
('Els Hoeven', 'els@teddykids.nl', 'Pedagogisch medewerker', 'active', 'Zoeterwoude'),
('Evangelia-Maria Kazolia', 'mariliakazolia@gmail.com', 'Pedagogisch medewerker', 'active', 'Den Haag'),
('Federica Gl Vigliarolo', 'federica.vigliarolo@libero.it', 'Pedagogisch medewerker', 'active', 'Leiderdorp'),
('Federica Meddi', 'meddifederica@gmail.com', 'Pedagogisch medewerker', 'active', 'Nieuw-Vennep'),
('Forough Shekari', 'forough.shekari@yahoo.com', 'Pedagogisch medewerker', 'active', 'Hazerswoude-Dorp'),
('Gabriella Gutierrez', 'gabygutierrez0526@gmail.com', 'Pedagogisch medewerker', 'active', '''s-Gravenhage'),
('Galyna Baklanova', 'galynaob277@gmail.com', 'Pedagogisch medewerker', 'active', 'Oegstgeest'),
('Hajar Bardaa', 'h_bardaa@outlook.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Hannah Leonora', 'hannahnoemi123@gmail.com', 'Pedagogisch medewerker', 'active', 'Rotterdam'),
('Hanrike Madgwick', 'hanrike@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Humaira Alifah Wardana', 'humaira.alifah02@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Ilham Bounouh', 'ilhambounouh@hotmail.nl', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Irine Vorisek', 'irine_vorisek@hotmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Jaclyn Misagal', 'jaclyn_misagal@yahoo.com', 'Pedagogisch medewerker', 'active', 'Alphen aan den Rijn'),
('Jady Gerardus', 'Jadygerardus@hotmail.com', 'Pedagogisch medewerker', 'active', 'Leiderdorp'),
('Jessica Otten-Koel', 'jesskoel@hotmail.com', 'Vestegingsmanager', 'active', 'Noordwijk'),
('Judit Santana Zamora', 'judit.santana.zamora@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Juliette Frederique de Mooij', 'Julliettedemooij@outlook.com', 'Pedagogisch medewerker in ontwikkeling', 'active', 'Rijnsburg'),
('Kethianna Oppenhuizen', 'kethianna.o@gmail.com', 'Pedagogisch medewerker', 'active', 'Zoeterwoude'),
('Kimberley Smit', 'apenstaartj_@hotmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Konstantina Zolota', 'zolota.constadina@gmail.com', 'Pedagogisch medewerker', 'active', 'Voorburg'),
('Lara Ferro Torres', 'ferrotorreslara@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Lucia Ribera Garcia', 'luciariberaaa@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Maeve Byrne', 'Maevebyrne2020@outlook.com', 'Pedagogisch medewerker', 'active', 'Voorschoten'),
('Maria Laura Crisetig', 'crislaura50@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Maud Kamstra', 'mkamstra31@gmail.com', 'Pedagogisch medewerker', 'active', 'Oegstgeest'),
('Meral Akdeniz', 'meralakdeniz@hotmail.com', 'Vestegingsmanager', 'active', 'Leiderdorp'),
('Monalisa Goon Hazra', 'monalisagoon@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Nadieżda Królik', 'nadia.krolik@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Nafiza Bholai Evers', 'nafiza1@hotmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Naramane Muriricho', 'Naramane@hotmail.com', 'Pedagogisch medewerker', 'active', 'Voorschoten'),
('Nazha Elgourari', 'n.azha__@live.nl', 'Pedagogisch medewerker', 'active', 'Bodegraven'),
('Nisrine Sebai', 'Nisrinesebai2004@icloud.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Octavia Octavia', 'piasimarmata@gmail.com', 'Pedagogisch medewerker', 'active', 'Hazerswoude-rijndijk'),
('Olivia Gadberry', 'gadberryolivia@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Ollga Mouska', 'olgamouska@gmail.com', 'Pedagogisch medewerker', 'active', 'Amsterdam'),
('Pamela Pradenas Farias', 'pamela@teddykids.nl', 'Vestegingsmanager', 'active', 'Noordwijkerhout'),
('Pleun Lustig', 'pleuntjelustig@hotmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Prachi Bahl', 'bahlprachi@yahoo.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Rachel Mulder', 'rachelmulder12@gmail.com', 'Pedagogisch medewerker', 'active', 'Utrecht'),
('Rene Dam', 'renedam1304@hotmail.com', 'Klusjesman', 'active', 'Alkmaar'),
('Renuka Ramasray', 'renuka.ramasray@hotmail.com', 'Pedagogisch medewerker', 'active', 'Utrecht'),
('Rita Akwana', 'ritaakwana@yahoo.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Snezana de Harde-Dimic', 'snezadeharde@gmail.com', 'Pedagogisch medewerker', 'active', 'Purmerend'),
('Sofia Nikou', 'nikousophia2@gmail.com', 'Pedagogisch medewerker', 'active', 'Rotterdam'),
('Sophia Grella', 'sophiagrella2002@gmail.com', 'Pedagogisch medewerker', 'active', 'Leiden'),
('Svetlana Bolotina', 'svetlana@teddykids.nl', 'Vestegingsmanager', 'active', 'Oegstgeest'),
('Taahiera Oemedali', 'Taahiera-oemedali@hotmail.com', 'Pedagogisch medewerker', 'active', 'Leiderdorp')
ON CONFLICT (full_name) DO NOTHING;