name: Deploy Supabase Functions

on:
  push:
    branches: [main, master]
    paths:
      - 'supabase/functions/**'
      - 'supabase/config.toml'
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Setup Supabase CLI
        uses: supabase/setup-cli@v1
        with:
          version: latest

      - name: Link Supabase project
        run: supabase link --project-ref ${{ secrets.SUPABASE_PROJECT_ID }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Deploy functions
        run: supabase functions deploy
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Set secrets
        run: |
          if [ -n "${{ secrets.EMPLOYES_API_KEY }}" ]; then
            echo "Setting EMPLOYES_API_KEY secret..."
            supabase secrets set EMPLOYES_API_KEY="${{ secrets.EMPLOYES_API_KEY }}"
          else
            echo "⚠️ EMPLOYES_API_KEY secret not found in GitHub secrets"
          fi
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - name: Send deployment notification
        if: always()
        run: |
          if [ "${{ job.status }}" = "success" ]; then
            echo "✅ Supabase functions deployed successfully!"
          else
            echo "❌ Supabase deployment failed!"
          fi